### ISSUE TITLE
Замечания

### ISSUE THREAD

**Issue by maximpetrov** [nikonufrienko/MyJavaHomeWorkTask1#1]
Обязательные:
1. Константы в `Java` принято именовать БОЛЬШИМИ_БУКВАМИ_ЧЕРЕЗ_ПОДЧЕРКИВАНИЕ.
2. Не везде используете константы, которые завели, а ещё явно не хватает константы 1.
3. Вместо `LinkedList` лучше использовать `ArrayList`. Единственное изменение структуры, которое Вы производите над ним, добавление в конец. С этим `ArrayList` справляется не хуже, чем `LinkedList`. А вот обращение по индексу, которое Вы используете почти везде, у `LinkedList` сильно медленнее.
4. Сравнить числа можно и без вычитания. Для сравнения не нужно заводить лишних структур, а если идти со старших разрядов, то это будет в среднем быстрее.
5. Исключение также следует кидать и при передаче в конструктор отрицательного числа.
6. Не хватает переопределения стандартного `equals` и `hashCode`.

Рекомендуемые:
1. Было бы эффективнее использовать в качестве хранимых элементов не `Character`, а `Integer`.
2. Умножение тоже можно было бы реализовать не побитно, а поэлементно, как сложение и вычитание.

**Comment by nikonufrienko** [comment]
Над `Integer` нельзя производить побитовый сдвиг влево, в отличии от `Character`. Если реализовывать все арифметически, то выйдет, что в каждой ячейке будет храниться один лишний бит.

**Comment by maximpetrov** [comment]
С чего Вы взяли, что над `Integer` нельзя производить побитовый сдвиг влево? И почему при "арифметической" реализации умножения будет лишний бит?

**Comment by nikonufrienko** [comment]
Я до этого пробовал использовать `Integer`, и он в некоторых случаях как-то себя странно вёл при побитовом сдвиге, после чего я и решил переписать все через `Character`, что как по мне в разы было проще чем костыльными методами пытаться заюзать весь диапазон значений инта (в плюсах к примеру арифметический сдвиг вправо для `int` сильно отличается от логического сдвиг для `unsigned int`).

**Comment by nikonufrienko** [comment]
Ну а лишний бит будет только в том случае, если для хранения числа использовать не весь диапазон значений инта, что сильно упрощает задачу в плане реализации умножения "умножением".

**Comment by maximpetrov** [comment]
Про сдвиги отчасти согласен, в Джаве сдвиги только арифметические, поэтому есть некоторые сложности, но они достаточно легко решаются. А вот с умножением всё ещё не понял, почему будет именно один лишний бит.

**Comment by nikonufrienko** [comment]
Я просто предполагал, что за счёт своей знаковости int ведёт себя иначе нежели чем unsigned int в плане умножения, сейчас я проверил и понял, что это не так и что любая комбинация значений инта при умножении даёт результат, соответствующий аналогичному для unsigned int.

**Comment by nikonufrienko** [comment]
Вроде я все исправил.

**Comment by maximpetrov** [comment]
1. Вы неправильно переопределили `equals`. Во-первых, `==` в Java сравнивает по ссылке, а надо бы по содержимому. Во-вторых, посмотрите, как принято писать `equals`, или сгенерируйте с помощью Idea.
2. `hashCode` тоже переопределён не очень хорошо. Обычно для получения хешкода элементы не просто складывают, а ещё на каждом шаге домножают результат, например, на 31, чтобы получить более равномерно распределённые значения. Его опять же можно сгенерить с помощью Idea. Но тут даже проще: Вы считаете хешкод только по списку, у которого тоже есть свой метод `hashCode`, который можно просто вызвать и вернуть результат.
3. Три метода сравнения очень похожи (особенно `isBiggerThan` и `isSmallerThan`). Было бы неплохо избавиться от дублирования кода, например, сделать один метод `compare` и использовать его в этих трёх.

**Comment by nikonufrienko** [comment]
Исправил.
